<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/request.proto

namespace GPBMetadata\Proto;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¿
proto/request.proto"
List
value (	"‚
Request
httpVersion (	
method (	
path (	&
headers (2.Request.HeadersEntry"
query (2.Request.QueryEntry
body (	5
HeadersEntry
key (	
value (2.List:83

QueryEntry
key (	
value (2.List:8"x
Response\'
headers (2.Response.HeadersEntry
body (	5
HeadersEntry
key (	
value (2.List:8B
Zmessage/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

