<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace GPBMetadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ô
messages.proto"
List
values (	"Ô
Request
httpVersion (	
method (	
path (	&
headers (2.Request.HeadersEntry"
query (2.Request.QueryEntry
body (	"
files (2.Request.FilesEntry.
HeadersEntry
key (	
value (	:83

QueryEntry
key (	
value (2.List:83

FilesEntry
key (	
value (2.File:8"…
Response

statusCode (\'
headers (2.Response.HeadersEntry
body (	.
HeadersEntry
key (	
value (	:8"7
File
filename (	
tmpPath (	
size (B
Zmessage/bproto3'
        , true);

        static::$is_initialized = true;
    }
}

